### ISSUE TITLE
aioworkers 0.13 support

### ISSUE THREAD

**Issue by abogushov** [aioworkers/aioworkers-redis#3]
AbstractNestedEntity.factory method has different signature in aioworkers 0.13. This is cause an error in aioworkers_redis.base.Connector

```
TypeError: factory() takes 2 positional arguments but 3 were given 
```

We need 2 releases:
0.4.4: requires aioworkers<0.13.0
0.5.0: requires aioworkers>=0.13.0

**Comment by aamalev** [comment]
@abogushov please replay this in test

**Comment by aamalev** [comment]
oh, https://github.com/aioworkers/aioworkers-redis/commit/945ac69ef26d5501edc02224013245797393b251
